/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Tactical Light Theme Design Tokens
        "surface-base": "#f8fafc",
        "surface-secondary": "#ffffff",
        "surface": "#ffffff",
        "surface-dim": "#f1f5f9",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "surface-variant": "#f1f5f9",
        "surface-tint": "#0284c7",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "inverse-surface": "#0f172a",
        "inverse-on-surface": "#f8fafc",
        "outline": "#94a3b8",
        "outline-variant": "#e2e8f0",
        "primary": "#0284c7",
        "on-primary": "#ffffff",
        "primary-container": "#0ea5e9",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#38bdf8",
        "primary-fixed": "#e0f2fe",
        "primary-fixed-dim": "#bae6fd",
        "on-primary-fixed": "#0369a1",
        "on-primary-fixed-variant": "#0284c7",
        "secondary": "#7c3aed",
        "on-secondary": "#ffffff",
        "secondary-container": "#8b5cf6",
        "on-secondary-container": "#ffffff",
        "secondary-fixed": "#ede9fe",
        "secondary-fixed-dim": "#ddd6fe",
        "on-secondary-fixed": "#5b21b6",
        "on-secondary-fixed-variant": "#6d28d9",
        "tertiary": "#0891b2",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#06b6d4",
        "on-tertiary-container": "#ffffff",
        "tertiary-fixed": "#cffafe",
        "tertiary-fixed-dim": "#a5f3fc",
        "on-tertiary-fixed": "#155e75",
        "on-tertiary-fixed-variant": "#0e7490",
        "threat-crimson": "#e11d48",
        "threat-crimson-dark": "#be123c",
        "risk-amber": "#d97706",
        "verified-emerald": "#059669",
        "ai-purple": "#7c3aed",
        "ai-purple-light": "#6d28d9",
        "error": "#dc2626",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        "card-glass": "rgba(255, 255, 255, 0.85)",
        "border-glass": "rgba(15, 23, 42, 0.08)",
        cyber: {
          950: '#ffffff',
          900: '#f8fafc',
          850: '#f1f5f9',
          800: '#e2e8f0',
          700: '#cbd5e1',
          border: 'rgba(15, 23, 42, 0.08)',
          neonBlue: '#0284c7',
          neonCyan: '#0891b2',
          neonEmerald: '#059669',
          neonAmber: '#d97706',
          neonRose: '#e11d48',
          neonPurple: '#7c3aed',
        }
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1.25rem",
        "space-xl": "2rem",
        "margin": "1rem",
        "margin-md": "1.5rem",
        "margin-lg": "2rem",
        "gutter": "1rem",
        "gutter-lg": "1.5rem"
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        "label-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      boxShadow: {
        'glow-cyan': '0 0 20px -3px rgba(6, 182, 212, 0.35)',
        'glow-rose': '0 0 20px -3px rgba(244, 63, 94, 0.4)',
        'glow-amber': '0 0 20px -3px rgba(245, 158, 11, 0.35)',
        'glow-emerald': '0 0 20px -3px rgba(16, 185, 129, 0.35)',
        'glow-purple': '0 0 25px -4px rgba(168, 85, 247, 0.4)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'radar-sweep': 'radar 4s linear infinite',
        'scanline': 'scanline 8s linear infinite',
      },
      keyframes: {
        radar: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        scanline: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(1000%)' },
        }
      }
    },
  },
  plugins: [],
}
